name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Hugging Face token
        run: git config --global credential.helper store && echo "https://huggingface-token:${{ secrets.HG }}@huggingface.co" > ~/.git-credentials
      
      - name: Push to Hugging Face
        run: |
          git remote set-url origin https://huggingface.co/spaces/tuankeued/demoZoro/
          git push origin main
